### ISSUE TITLE
You should change this!

### ISSUE THREAD

**Issue by jojomondag** [WilleLX1/WilleLX1.github.io#1]
In your Github.io Page dont show 

Hej, jag heter William Danielsson. Reklamutdelare Jag är en reklam utdelare från Helsingborg, Sverige.Kontakta Mig

Jag är en reklam utdelare från Helsingborg, Sverige.

That infomation should not be you main information. Instead change it to 

01. Om Mig 
Hej! Jag heter William, jag går på NTI gymnasiumet i Helsingborg med teknik inriktning.
Just nu är jag reklam utdelare med svensk direkt reklam.
Några programmerings språk eller program jag gärna använder mig av:

This information is much mor intressting for a person that visits your page!

**Comment by WilleLX1** [comment]
Hello,

Thank you for your feedback and the suggested changes to my Github.io site. I want to make sure I understand your request clearly, and I believe you're asking to replace the current main title on my website with the "Om Mig" section, correct? This means that the "Om Mig" section would be the first thing visitors see when they land on the page.

To implement this change, the best way to proceed would be through a pull request on my Github repository. If you're comfortable with Git and GitHub, you could make the changes directly and create a pull request.

Your input is valuable, and I'm committed to making these improvements to my Github.io site. Thank you for your support!

Best regards,
William

**Comment by jojomondag** [comment]
Im not doing it, you should do it if you agree with my message!

**Comment by WilleLX1** [comment]
Okay
